### ISSUE TITLE
Not an  Issue: Jasper report  export to PDF in spring batch for multiple PDF

### ISSUE THREAD

**Issue by vikasjadhav30** [Jaspersoft/jasperreports-modern-pdf#1]
I need to export jasper report to pdf in spring batch application.
Scenario: using one jasper report layout and  text file (data) have multiple rows (consider each row for single(account)) used as a data to fill  report. In spring batch application i have to create only one pdf for  all rows(accounts). using exportReportToPdfFile() it will  export all accounts at a time , however i have to use batch processing and need to write pdf row by row(accounts). Is there any way to do so?
I have checked with  **batch mode exporting**  where exporter loops through this list of reports and produces a single document from them. but what if we have millions of reports it wont be applicable.

**Comment by teodord** [comment]
This is an issue related to the JasperReports Library project. Here, we are in a project that provides an alternate PDF exporter using iText 5. This project here is not even released yet and still a work in progress.
We'll follow-up on this at:
https://community.jaspersoft.com/questions/1078756/jasper-report-export-pdf-spring-batch-multiple-pdf
